version: 1.0.{build}
build:
  verbosity: minimal

notifications:
- provider: Email
  to:
  - breno@martinusso.com
  subject: DocsBr.Net Build
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
