# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build & Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Install .NET Framework 4.5.2 Developer Pack
      run: |
          Invoke-WebRequest -Uri 'https://download.visualstudio.microsoft.com/download/pr/97f48e91-6458-450a-93a8-48b0cdd950d9/54e7d1d287340f1a941f10738d8109d9/NDP452-KB2901951-x86-x64-DevPack.exe' -OutFile 'NDP452-KB2901951-x86-x64-DevPack.exe'
          Start-Process -Wait -FilePath 'NDP452-KB2901951-x86-x64-DevPack.exe' -ArgumentList '/q'
      shell: pwsh
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
